apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-pg-super-user
  namespace: {{ .Release.Namespace }}
type: Opaque
stringData:
  superUserPassword: super_pwd
  replicationUserPassword: replica_pwd
